### ISSUE TITLE
Не работает конкатенация с вызовом метода

### ISSUE THREAD

**Issue by ydergachev-gsg** [nikolaygekht/luax#2]
```
var terminal: ITerminal;
var message: string;
...
message = "Terminal type. expected '" .. TerminalType.TRADING .. "', actual '" .. terminal.getType() .. "'";
                                                                               ^
```

При компиляции выдает ошибку:
```
Unhandled exception. Luax.Parser.Ast.LuaXAstGeneratorException: TerminalTest.luax(15,88) : 
The class name or an object expression is expected here
```

Если terminal.getType() заменить на переменную, отработает без ошибок.

**Comment by nikolaygekht** [comment]
пофикшено в сегодняшнем изменении грамматики - не правильно был приоритет у . в момент call - ниже чем у остальных операторов, а должен быть выше.

**Comment by nikolaygekht** [comment]
см. тест
https://github.com/nikolaygekht/luax/blob/a2af058ec74d11faebc2f000b6634aca29dc0728/LuaX.Test/expressionTest.luax#L24
